name: llama-final-tested-env-v3
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
  - numpy<2.0
  - torch==2.1.0 --index-url https://download.pytorch.org/whl/cu121
  - torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cu121
  - transformers==4.52.4
  - tokenizers==0.15.2
  - datasets==3.6.0
  - accelerate==1.7.0
  - peft==0.15.2
  - bitsandbytes==0.41.3
  - trl==0.7.10
  - huggingface-hub==0.32.4
  - wandb==0.20.0
  - scikit-learn
  - nltk
  - azureml-core==1.60.0.post1
  - mlflow==2.22.0
  - pandas
  - tqdm
  - pyyaml
  - jsonlines
  - rouge-score
  - sentence-transformers
  # ONLY ADDITION: Unsloth
  - git+https://github.com/unslothai/unsloth.git