name: llama-3b-finetune-env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - pip:
    - numpy<2.0
    - torch==2.1.0
    - transformers==4.37.0  # Updated for better Llama 3 support
    - datasets==2.16.0
    - accelerate==0.26.0
    - peft==0.7.1  # For LoRA
    - bitsandbytes==0.42.0  # For 4-bit quantization
    - trl==0.7.10  # For supervised fine-tuning
    - huggingface-hub==0.20.0
    - wandb==0.16.0
    - scikit-learn
    - nltk
    - azureml-core==1.55.0
    - mlflow==2.9.0
    - pandas
    - tqdm
    - pyyaml
    - jsonlines
    - rouge-score
    - sentence-transformers
    - einops  # Required for some Llama models
    - scipy
    - sentencepiece  # Required for Llama tokenizer
    - protobuf