name: llama-inference-env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - pip
  - pip:
    - torch>=2.0.0
    - transformers>=4.36.0
    - peft>=0.7.0
    - bitsandbytes>=0.41.0
    - accelerate>=0.24.0
    - git+https://github.com/unslothai/unsloth.git
    - mlflow>=2.8.0
    - pandas>=2.0.0
    - numpy>=1.24.0
    - python-dotenv>=1.0.0
    - pyyaml>=6.0
    - flask>=2.3.0
    - gunicorn>=21.2.0